version: '3.3'
services:
    dp-cantabular-metadata-exporter:
        build:
            context: ../../../dp-cantabular-metadata-exporter
            dockerfile: Dockerfile.local
        command:
            - go 
            - test 
            - -cover 
            - -coverpkg=github.com/ONSdigital/dp-cantabular-metadata-exporter/... 
            - -component
        volumes:
            - ../../:/dp-cantabular-metadata-exporter
        depends_on:
            - kafka
            - minio
            - vault
        ports:
            - 26700:26700
        environment:
            BIND_ADDR:                   ":26700"
            COMPONENT_TEST_USE_LOG_FILE: "${COMPONENT_TEST_USE_LOG_FILE-false}"
            DATASET_API_URL:             "http://dp-dataset-api:22000"
            KAFKA_ADDR:                  "kafka:9092"
            LOCAL_OBJECT_STORE:          "http://minio:9000"
            MINIO_ACCESS_KEY:            "minio-access-key"
            MINIO_SECRET_KEY:            "minio-secret-key"
            PUBLIC_BUCKET:               "dp-cantabular-metadata-exporter-pub"
            PRIVATE_BUCKET:              "dp-cantabular-metadata-exporter-priv"
            SERVICE_AUTH_TOKEN:          "testToken"
            VAULT_ADDR:                  "http://vault:8200"
            VAULT_TOKEN:                 "0000-0000-0000-0000"
