---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.1

inputs:
  - name: dp-cantabular-metadata-exporter

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-cantabular-metadata-exporter/ci/scripts/build.sh
